export type Permission = 'READ_PROGRAMME' | 'EDIT_PROGRAMME' | 'CREATE_PROGRAMME_VERSION' | 'SUBMIT_PROGRAMME_VERSION' | 'READ_EVIDENCE' | 'ADD_EVIDENCE' | 'READ_ASSESSMENT' | 'CREATE_ASSESSMENT' | 'EDIT_ASSESSMENT' | 'CREATE_FINDING' | 'EDIT_FINDING' | 'CREATE_ACTION' | 'EDIT_ACTION' | 'VERIFY_ACTION' | 'READ_ACCREDITATION' | 'MANAGE_ACCREDITATION_PROCESS' | 'READ_RVH_MATERIALS' | 'MAKE_RVH_DECISION' | 'READ_PORTFOLIO' | 'READ_QUALITY_DASHBOARD' | 'MANAGE_USERS' | 'MANAGE_CONFIGURATION'

export const rolePermissions: Record<string, Permission[]> = {
  GARANT_SP: ['READ_PROGRAMME', 'EDIT_PROGRAMME', 'CREATE_PROGRAMME_VERSION', 'SUBMIT_PROGRAMME_VERSION', 'READ_EVIDENCE', 'ADD_EVIDENCE', 'READ_ASSESSMENT', 'CREATE_FINDING', 'CREATE_ACTION', 'EDIT_ACTION', 'READ_ACCREDITATION'],
  KOORDINATOR_SP: ['READ_PROGRAMME', 'CREATE_PROGRAMME_VERSION', 'READ_EVIDENCE', 'ADD_EVIDENCE', 'READ_ASSESSMENT', 'READ_ACCREDITATION'],
  CLEN_RADY_SP: ['READ_PROGRAMME', 'READ_EVIDENCE', 'READ_ASSESSMENT', 'READ_ACCREDITATION', 'READ_PORTFOLIO'],
  HODNOTITEL_PS: ['READ_PROGRAMME', 'READ_EVIDENCE', 'READ_ASSESSMENT', 'CREATE_ASSESSMENT', 'EDIT_ASSESSMENT', 'CREATE_FINDING'],
  PREDSEDA_PS: ['READ_PROGRAMME', 'READ_EVIDENCE', 'READ_ASSESSMENT', 'CREATE_ASSESSMENT', 'EDIT_ASSESSMENT', 'CREATE_FINDING', 'READ_PORTFOLIO'],
  CLEN_RVH: ['READ_PROGRAMME', 'READ_EVIDENCE', 'READ_ASSESSMENT', 'READ_ACCREDITATION', 'READ_RVH_MATERIALS', 'MAKE_RVH_DECISION'],
  PRACOVNIK_ODBORU_KVALITY: ['READ_PROGRAMME', 'READ_EVIDENCE', 'READ_ASSESSMENT', 'READ_ACCREDITATION', 'MANAGE_ACCREDITATION_PROCESS', 'READ_PORTFOLIO', 'READ_QUALITY_DASHBOARD'],
  FAKULTNI_KOORDINATOR_KVALITY: ['READ_PROGRAMME', 'READ_EVIDENCE', 'READ_ASSESSMENT', 'READ_ACCREDITATION', 'MANAGE_ACCREDITATION_PROCESS', 'READ_PORTFOLIO'],
  VEDENI_FAKULTY: ['READ_PROGRAMME', 'READ_ACCREDITATION', 'READ_PORTFOLIO', 'READ_QUALITY_DASHBOARD'],
  VEDENI_UNIVERZITY: ['READ_PROGRAMME', 'READ_ACCREDITATION', 'READ_PORTFOLIO', 'READ_QUALITY_DASHBOARD'],
  EXTERNI_AUDITOR: ['READ_PROGRAMME', 'READ_EVIDENCE', 'READ_ASSESSMENT', 'CREATE_ASSESSMENT', 'CREATE_FINDING'],
  ADMIN: ['MANAGE_USERS', 'MANAGE_CONFIGURATION', 'READ_PORTFOLIO'],
}