from enum import StrEnum


class EvidenceType(StrEnum):
    STRUCTURED_DATA = "STRUCTURED_DATA"
    DOCUMENT = "DOCUMENT"
    CURRICULUM_MAP = "CURRICULUM_MAP"
    QUALITY_INDICATOR = "QUALITY_INDICATOR"
    STAKEHOLDER_FEEDBACK = "STAKEHOLDER_FEEDBACK"
    MEETING_RECORD = "MEETING_RECORD"
    OTHER = "OTHER"