export type CouncilTable = { number: number; title: string; purpose: string; columns: string[]; rows: string[][]; comment: string; conclusion: string }
const tables: [string, string, string[], string[][], string, string][] = [
['Návrhy opatření a plán zlepšování z minulého jednání a stav plnění','Carry forward previous actions',['Návrh opatření','Odpovědná osoba','Kroky realizace','Termíny','Očekávaný přínos','Indikátor úspěchu (KPI)','Stav plnění kroků realizace'],[['Výjezdy na SŠ Sokolská','Jan Novák','návštěva DoD; přednáška; dílna','22. 10. 2026; listopad 2026','Zvýšení počtu uchazečů','Navýšení o 5 %','Víkendová dílna se neuskutečnila']], 'Stav realizace navazuje na předchozí jednání.', 'Pokračující opatření vyžadují další kontrolu.' ],
['Vyhodnocení realizovaných dopadů opatření','Evaluate realised impacts',['Návrh opatření','Aktuální odpovědná osoba/osoby','Měřitelné dopady (KPI)','Zhodnocení dopadu','Další kroky, poznámka'],[['Výjezdy na SŠ Sokolská','Jan Novák','Uchazeči +3 %','Je to dobré, ale málo','Přidat víkendovou dílnu']], 'Dopad je třeba interpretovat v kontextu trendu.', 'Doporučeno sledovat KPI další rok.' ],
['Počty zaplacených přihlášek, přijatých a zapsaných uchazečů','Data z IS pro trend poptávky',['Rok','Zaplacené přihlášky','Počet přijatých','Počet zapsaných'],[['2021','122','102','71'],['2022','95','74','51'],['2023','88','76','58'],['2024','87','75','56'],['2025','78','68','45'],['2026','70','—','—']], 'V roce 2021 byla velká medializace; poté mírný pokles.', 'Poptávku dále sledovat.' ],
['Počty studujících, zastoupení žen mezi studujícími','Enrollment and gender composition',['Ak. rok','Ženy','Muži','Celkem','Procentuální zastoupení žen'],[['2020/21','15','53','68','24 %'],['2021/22','10','56','66','15 %'],['2022/23','7','43','50','14 %'],['2023/24','3','55','58','5 %'],['2024/25','4','54','58','7 %'],['2025/26','4','42','46','9 %']], 'Ubývá studentek; kapacita na opatření je omezená.', 'Téma zařadit mezi rizika.' ],
['Počty studentů na začátku studia, průchodnost studiem, počty absolventů','Cohort progression',['Ak. rok','Poč. stud. v 1. roč.','Poč. stud. ve 2. roč.','Poč. stud. ve 3. roč.','Poč. absolventů'],[['2021/22','28','32','18','18'],['2022/23','25','27','18','17'],['2023/24','23','23','15','15'],['2024/25','22','21','13','12'],['2025/26','24','20','14','14']], 'Studenti se kupí ve 2. ročníku.', 'Identifikovat bariéry průchodnosti.' ],
['Průměrná doba studia','Study duration trend',['Ak. rok','Prům. doba stud. (roky)'],[['2021/22','3,85'],['2022/23','3,42'],['2023/24','3,28'],['2024/25','3,14'],['2025/26','3,36']], 'Mírný pokles, letos anomálie.', 'Zatím bez opatření, sledovat.' ],
['Počet FTE na ústavu garanta + rozpad','Staff capacity',['Nákladové středisko Org.','Okruh pracovníků','Počet zaměstnanců','Součet měsíčních FTE','Průměrný úvazek'],[['Ústav Z','docent','14','143,60','0,85'],['Ústav Z','odborný asistent','20','223,70','0,93'],['Ústav Z','profesor','4','43,20','0,90']], 'Ústav c má málo profesorů, ale potenciál v docentech.', 'Personální riziko sledovat.' ],
['Výčet garantů předmětů zařazených do programu','Course guarantor workload',['Jméno garanta','Počty na FSI','Počty mimo FSI'],[['A (garant SP)','4','0'],['B','1','5'],['C','10','0'],['D','4','0'],['E','3','0']], 'Garant C je přetížen; garant B je odborně důležitý.', 'Navrhnout nástupnictví.' ],
['Počty závěrečných prací + maximální počet vedených BP a DP','Thesis capacity',['Ak. rok','Přiděleno','Obhájeno'],[['2021/22','13','12'],['2022/23','15','14'],['2023/24','12','12'],['2024/25','10','9'],['2025/26','11','—'],['Celkový výsledek','61','47']], 'Počty odpovídají kapacitě pracoviště.', 'Sledovat neobhájené práce.' ],
['Počty vedených ZP na každého vyučujícího ústavu','Individual thesis load',['Jméno vyučujícího','Počty vedení ZP'],[['A','12'],['B','3'],['C','0'],['D','1'],['E','8']], 'Vyučující A je přetížen.', 'Prověřit rozložení vedení.' ],
['Mobility studentů a zaměstnanců','Internationalisation trend',['Akademický rok','Počty studentů','Počty zaměstnanců'],[['2021/22','8','12'],['2022/23','2','4'],['2023/24','3','8'],['2024/25','5','16'],['2025/26','1','3']], 'Rok 2022/23 ovlivnil covidový propad.', 'Věnovat se internacionalizaci.' ],
['3 nejhůře hodnocené předměty v zimním semestru za poslední 2 roky','Student feedback: winter courses',['Zkratka','Název předmětu','Garant předmětu','Výsledné hodnocení'],[['LPS','a','x','1,45'],['LFI','b','y','2,11'],['LK','c','z','2,55'],['LMJ','d','s','1,71']], 'Předmět d po inovaci zmizel; c se opakuje.', 'Sledovat opakující se předměty.' ],
['3 nejhůře hodnocené předměty v letním semestru za poslední 2 roky','Student feedback: summer courses',['Zkratka','Název','Garant','Výsledné hodnocení'],[['LDS','e','k','1,38'],['LMT','f','l','1,55'],['RIT','g','m','1,58'],['IET','h','n','1,50']], 'Předmět g se opakuje, hodnocení je dobré.', 'Zpětná vazba je celkově dobrá.' ],
['3 nejhůře hodnocení vyučující v zimním semestru za poslední 2 roky','Teaching development: winter',['Vyučující','Zkratka','Název','Výsledné hodnocení'],[['A','LFI','x','1,78'],['B','LFI','y','2,45'],['C','LK','z','2,55']], 'A a B potřebují rozvoj pedagogických kompetencí.', 'Najít školení nebo mentoring.' ],
['3 nejhůře hodnocení vyučující v letním semestru za poslední 2 roky','Teaching development: summer',['Vyučující','Zkratka','Název','Výsledné hodnocení'],[['d','LMT','x','1,55'],['e','RIT','y','1,58'],['f','IPT-A','z','1,70']], 'Hodnocení je dobré, opatření není třeba.', 'Bez nového opatření.' ],
['Identifikace problémů a rizik','Problems and risks',['Identifikovaný problém','Dopad na kvalitu','Priorita','Odkaz na data'],[['Mírný pokles počtu uchazečů','Problematická udržitelnost','Nízká','Tabulka č. 3'],['Hromadění studentů v 2. ročníku','Může odrazovat uchazeče','Vysoká','Tabulka č. 5'],['Vyšší průměrná doba studia','Může odrazovat uchazeče','Střední','Tabulka č. 6'],['Opakující se horší hodnocení vyučujících','Snižuje motivaci studentů','Střední','Tabulka č. 14']], 'Vysoká priorita se propíše do nových opatření.', 'Priorita: bariéry průchodnosti.' ],
['Návrhy opatření, plán zlepšování – původní, pokračující','Continuing improvement actions',['Návrh opatření','Odpovědná osoba','Kroky realizace','Termíny','Očekávaný přínos','Indikátor úspěchu (KPI)'],[['Výjezdy na SŠ Sokolská','Jan Novák','víkendová dílna','jaro 2027','Zvýšení počtu uchazečů','+5 %'],['Zařazení odborníků z praxe','Petr Bílý','oslovení Škoda Auto','říjen 2027','Zlepšení výsledků 2. ročníku','+10 %']], 'Navazuje na tabulku 2.', 'Pokračovat v realizaci.' ],
['Návrhy opatření, plán zlepšování – nové, které nyní vznikly','New improvement actions',['Návrh opatření','Odpovědná osoba','Kroky realizace','Termíny','Očekávaný přínos','Indikátor úspěchu (KPI)'],[['Bariéry průchodnosti ve 2. r.','Pavel Kratochvíl','identifikace problémů; úprava předmětů','prosinec 2027; duben 2028','Zvýšení průchodnosti 2.–3. ročník','alespoň 80 %']], 'Nové opatření vzniká z tabulky 16.', 'Zařadit do plánu zlepšování.' ],
]
export const councilTables: CouncilTable[] = tables.map(([title, purpose, columns, rows, comment, conclusion], index) => ({ number: index + 1, title, purpose, columns, rows, comment, conclusion }))
export const councilSections = ['Základní údaje', 'Návaznost na předchozí jednání', 'Kvantitativní charakteristiky', 'Zpětná vazba od studujících', 'Kvalitativní charakteristiky', 'Problémy a rizika', 'Opatření a plán zlepšování']
