import { useState } from 'react'
import { gCriteria, hCriteria, rCriteria, prCriteria, findingCategories, evidenceRegister, traceability, type MethodologyCriterion } from '../content/methodologyCatalog'
import { roleLabels } from '../presentation/roleLabels'
import type { RoleAssignment } from '../auth/roles'

export function MethodologyPage({ assignment }: { assignment: RoleAssignment }) { const [section, setSection] = useState('G'); const catalog = section === 'G' ? gCriteria : section === 'H' ? hCriteria : section === 'R' ? rCriteria : prCriteria; return <div className="content-frame methodology-page"><div className="page-heading"><div><span className="eyebrow">AUTORITATIVNÍ METODIKA · {roleLabels[assignment.role]}</span><h1>Hodnocení kvality</h1><p className="page-description">Kompletní checklisty G/H/R/PR, důkazní registr a návaznost podle metodiky RVH.</p></div><MethodologyLegend /></div><div className="methodology-tabs">{['G','H','R','PR','Důkazy','Návaznost','Souhrny'].map((item) => <button type="button" className={section === item ? 'active' : ''} onClick={() => setSection(item)} key={item}>{item === 'Důkazy' ? 'Registr důkazů' : item === 'Návaznost' ? 'G–H–R map' : item === 'Souhrny' ? 'Souhrny a rozhodnutí' : `Checklist ${item}`}</button>)}</div>{['G','H','R','PR'].includes(section) ? <Checklist criteria={catalog} label={section} /> : section === 'Důkazy' ? <EvidenceRegister /> : section === 'Návaznost' ? <Traceability /> : <Summaries />}</div> }

function Checklist({ criteria, label }: { criteria: MethodologyCriterion[]; label: string }) { const [filter, setFilter] = useState('Vše'); const shown = criteria.filter((item) => filter === 'Vše' || item.classification.includes(filter)); return <><div className="methodology-summary"><Metric label={`Celkem ${label} kritérií`} value={String(criteria.length)} /><Metric label="Splněno" value={label === 'G' ? '42' : '—'} /><Metric label="Částečně" value={label === 'G' ? '18' : '—'} /><Metric label="Nesplněno" value={label === 'G' ? '3' : '—'} /><Metric label="Bez důkazu" value={label === 'G' ? '9' : '—'} /></div><div className="methodology-filters">{['Vše','P','E27','F'].map((item) => <button className={filter === item ? 'active' : ''} type="button" onClick={() => setFilter(item)} key={item}>{item}</button>)}</div><div className="criterion-list">{shown.map((criterion) => <details className="criterion-item" key={criterion.id}><summary><span className="criterion-id">{criterion.id}</span><span className="criterion-section">{criterion.section}</span><span className={`criterion-class criterion-${criterion.classification.replace('/','-')}`}>{criterion.classification}</span><span className="criterion-effect">{criterion.decisionEffect}</span><span className="criterion-status">Nehodnoceno</span></summary><div className="criterion-detail"><p><strong>Kontrolní otázka</strong>{criterion.question}</p><p><strong>Očekávaný důkaz</strong>{criterion.evidence}</p><div className="criterion-meta"><span>Evidence: ID / D0–D3</span><span>Vlastník: Garant SP</span><span>Vazby: {criterion.links}</span></div></div></details>)}</div></> }
function EvidenceRegister() { return <section className="methodology-panel"><div className="section-panel-header"><div><span className="eyebrow">PŘÍLOHA B</span><h2>Registr důkazů</h2><span className="section-caption">ID důkazu se používá shodně v G, H, stanovisku PS i rozhodnutí RVH.</span></div></div><div className="evidence-register">{evidenceRegister.map((item) => <div className="evidence-register-row" key={item.id}><strong>{item.id}</strong><span>{item.title}<small>{item.reference}</small></span><span>{item.owner}</span><span>{item.date}</span><b>{item.strength}</b><span>{item.usedBy}</span></div>)}</div></section> }
function Traceability() { return <section className="methodology-panel"><div className="section-panel-header"><div><span className="eyebrow">PŘÍLOHA C</span><h2>Návaznost G–H–R</h2><span className="section-caption">RVH nesmí použít rozhodovací důvod, který není dohledatelný přes H k G a důkazu.</span></div></div><div className="trace-map">{traceability.map((row) => <div className="trace-map-row" key={row.area}><strong>{row.area}</strong><span>{row.g}</span><span>{row.h}</span><span>{row.r}</span></div>)}</div></section> }
function Summaries() { return <div className="summary-grid"><section className="methodology-panel"><h2>Výstup sebehodnocení garanta</h2><SummaryRow label="P – závazné minimum" value="Počet N: 3 · Počet C: 18 · Připraveno: ano" /><SummaryRow label="E27 – připravenost" value="Tři nejsilnější stránky · hlavní mezery" /><SummaryRow label="F – strategická hodnota" value="Proharmonizační / neutrální / fragmentační" /><SummaryRow label="N/R" value="Seznam ID a odůvodnění" /><SummaryRow label="Rizika" value="Riziko · vlastník · reakce · spouštěč · přezkoumání" /><SummaryRow label="Opatření" value="Vlastník · termín · účinek · ověření" /></section><section className="methodology-panel"><h2>Kategorizace zjištění</h2>{findingCategories.map((item) => <div className="finding-category" key={item.id}><b>{item.id}</b><strong>{item.name}</strong><span>{item.effect}</span></div>)}</section><section className="methodology-panel decision-sheet"><span className="eyebrow">TABULKA 30</span><h2>Rozhodovací list RVH</h2>{['A. Platné minimum','B. Kvalita / ESG 2027','C. Strategická hodnota','D. Portfolio','E. Proces','Výrok'].map((item) => <SummaryRow label={item} value="Výběr dle metodiky · odůvodnění / vazba" key={item} />)}</section></div> }
function SummaryRow({ label, value }: { label: string; value: string }) { return <div className="summary-row"><strong>{label}</strong><span>{value}</span></div> }
function Metric({ label, value }: { label: string; value: string }) { return <div><span>{label}</span><strong>{value}</strong></div> }
function MethodologyLegend() { return <details className="methodology-legend"><summary>Legenda metodiky</summary><div><strong>P</strong><span>Závazné minimum</span><strong>E27</strong><span>Rozvojový standard</span><strong>F</strong><span>Strategické kritérium</span><strong>A / C / N / N/R</strong><span>Ano / Částečně / Ne / Nerelevantní</span><strong>D0–D3</strong><span>Úrovně síly důkazu</span></div></details> }
