import type { RoleAssignment } from '../auth/roles'
import { can } from '../auth/access'
import { roleLabels, scopeLabels } from '../presentation/roleLabels'
import { workspaceAttention } from '../mock/workspace'

const roleMessages: Record<string, string> = { GARANT_SP: 'Co musím jako garant řešit?', KOORDINATOR_SP: 'Co je potřeba připravit a doplnit?', CLEN_RADY_SP: 'Co má rada programu projednat?', HODNOTITEL_PS: 'Co mám posoudit?', PREDSEDA_PS: 'Je pracovní skupina připravena uzavřít hodnocení?', CLEN_RVH: 'Co čeká na rozhodnutí RVH?', PRACOVNIK_ODBORU_KVALITY: 'Co se děje napříč VUT a kde je potřeba metodický zásah?', FAKULTNI_KOORDINATOR_KVALITY: 'Co vyžaduje pozornost na fakultě?', VEDENI_FAKULTY: 'Jaké jsou strategické a kvalitativní priority fakulty?', VEDENI_UNIVERZITY: 'Jaký je stav portfolia a systému kvality VUT?', EXTERNI_AUDITOR: 'Co je v rámci tohoto auditu zpřístupněno k posouzení?', ADMIN: 'Jak je nastavený systém a kdo k němu má přístup?' }

export function RoleWorkspacePage({ assignment }: { assignment: RoleAssignment }) {
  const role = assignment.role
  const isExternal = role === 'EXTERNI_AUDITOR'
  return <div className="content-frame role-workspace"><div className="role-heading"><div><span className="eyebrow">{isExternal ? 'OMEZENÝ AUDITNÍ PROSTOR' : 'ROLE-AWARE WORKSPACE'}</span><h1>{roleMessages[role]}</h1><p className="page-description">{roleLabels[role]} · {scopeLabels[assignment.scopeType]}{assignment.scopeId ? ` · ${assignment.scopeId}` : ''}</p></div><div className="role-chip"><strong>{roleLabels[role]}</strong><span>{scopeLabels[assignment.scopeType]}</span></div></div>{isExternal && <div className="audit-banner"><strong>Externí audit – omezený přístup</strong><span>EUR-ACE / Procesní inženýrství / ProgrammeVersion 3</span><small>Platný přístup: {assignment.validFrom} – {assignment.validTo}</small></div>}<WorkspaceBody assignment={assignment} /></div>
}

function WorkspaceBody({ assignment }: { assignment: RoleAssignment }) {
  const role = assignment.role
  if (role === 'ADMIN') return <AdminBody />
  if (role === 'EXTERNI_AUDITOR') return <AuditorBody assignment={assignment} />
  if (role === 'VEDENI_UNIVERZITY' || role === 'VEDENI_FAKULTY') return <LeadershipBody role={role} />
  if (role === 'CLEN_RVH') return <RvhBody assignment={assignment} />
  if (role === 'HODNOTITEL_PS' || role === 'PREDSEDA_PS') return <ReviewTeamBody assignment={assignment} />
  if (role === 'CLEN_RADY_SP') return <CouncilBody assignment={assignment} />
  if (role === 'KOORDINATOR_SP') return <CoordinatorBody assignment={assignment} />
  if (role === 'FAKULTNI_KOORDINATOR_KVALITY' || role === 'PRACOVNIK_ODBORU_KVALITY') return <QualityOfficeBody role={role} />
  return <GuarantorBody assignment={assignment} />
}

function GuarantorBody({ assignment }: { assignment: RoleAssignment }) { return <div className="role-grid"><WorkspaceCard title="Můj studijní program" label="N-PI · Procesní inženýrství"><div className="role-stat-grid"><Metric label="Otevřená zjištění" value="2" /><Metric label="Moje opatření" value="3" /><Metric label="Chybějící důkazy" value="3" /><Metric label="Připravované verze" value="1" /></div></WorkspaceCard><WorkspaceCard title="Moje další kroky" label="Akce podle oprávnění"><RoleTask title="Doplnit důkaz k H11" detail="Procesní inženýrství · do 30. 6. 2027" action={can(assignment, 'ADD_EVIDENCE') ? 'Přidat důkaz' : undefined} /><RoleTask title="Připravit Verzi 4" detail="Plánovaná účinnost 2030/2031" action={can(assignment, 'CREATE_PROGRAMME_VERSION') ? 'Nová verze' : undefined} /><RoleTask title="Odpovědět na zjištění" detail="Vyšší podíl projektové výuky" action={can(assignment, 'CREATE_ACTION') ? 'Navrhnout opatření' : undefined} /></WorkspaceCard><SharedSignals /></div> }
function CoordinatorBody({ assignment }: { assignment: RoleAssignment }) { return <div className="role-grid"><WorkspaceCard title="Příprava podkladů" label="Administrativní fronta"><RoleTask title="Dokumenty k doplnění" detail="Kurikulární mapa · Procesní inženýrství" action={can(assignment, 'ADD_EVIDENCE') ? 'Doplnit' : undefined} /><RoleTask title="Chybějící údaje ve Verzi 4" detail="ProgrammeVersion · 2030/2031" action="Kontrolní seznam" /><RoleTask title="Úkoly od garanta" detail="3 nové položky" action="Otevřít" /></WorkspaceCard><WorkspaceCard title="Termíny" label="Bez rozhodovací pravomoci"><div className="deadline-list"><div><time>30. 9. 2027</time><span>Předložení podkladů fakultě</span></div><div><time>15. 10. 2027</time><span>Doplnění dokumentace</span></div></div></WorkspaceCard></div> }
function CouncilBody({ assignment }: { assignment: RoleAssignment }) { return <div className="role-grid"><WorkspaceCard title="Rada studijního programu" label="N-PI · podklady k projednání"><div className="role-stat-grid"><Metric label="Indikátory" value="5" /><Metric label="Otevřená zjištění" value="2" /><Metric label="Otevřená opatření" value="3" /></div></WorkspaceCard><WorkspaceCard title="Příští jednání" label="12. 12. 2027"><RoleTask title="H11 · Zpětná vazba studentů" detail="Materiál čeká na projednání" action={can(assignment, 'READ_ASSESSMENT') ? 'Prohlédnout' : undefined} /><RoleTask title="Výsledky kvality 2026" detail="Indikátory a stakeholder feedback" action="Otevřít materiály" /></WorkspaceCard></div> }
function ReviewTeamBody({ assignment }: { assignment: RoleAssignment }) { return <div className="role-grid"><WorkspaceCard title={assignment.role === 'PREDSEDA_PS' ? 'Stav pracovní skupiny' : 'Moje přidělená hodnocení'} label="Akreditační proces · N-PI"><div className="role-stat-grid"><Metric label="Požadavky k posouzení" value={assignment.role === 'PREDSEDA_PS' ? '6' : '2'} /><Metric label="Hotová hodnocení" value={assignment.role === 'PREDSEDA_PS' ? '4' : '1'} /><Metric label="Chybějící důkazy" value="2" /><Metric label="Zjištění" value="1" /></div></WorkspaceCard><WorkspaceCard title="Pracovní fronta" label={assignment.role === 'PREDSEDA_PS' ? 'Připravenost k závěru' : 'Termíny a podklady'}><RoleTask title="G27 · Kurikulární provázanost" detail="Evidence: 1 · pracovní návrh hodnocení" action={can(assignment, 'CREATE_ASSESSMENT') ? 'Vytvořit hodnocení' : undefined} /><RoleTask title="Neshoda v posouzení H05" detail="Vyžaduje moderaci předsedy PS" action={assignment.role === 'PREDSEDA_PS' ? 'Vyřešit neshodu' : undefined} /></WorkspaceCard></div> }
function RvhBody({ assignment }: { assignment: RoleAssignment }) { return <div className="role-grid"><WorkspaceCard title="Případy čekající na projednání" label="RVH · globální rozsah"><RoleTask title="Procesní inženýrství · Verze 4" detail="Stanovisko pracovní skupiny připraveno" action={can(assignment, 'READ_RVH_MATERIALS') ? 'Otevřít podklady' : undefined} /><RoleTask title="Energetické inženýrství · Verze 1" detail="Externí NAÚ · předloženo" action="Prohlédnout" /></WorkspaceCard><WorkspaceCard title="Rozhodovací materiály" label="Formální rozhodování oddělené od workflow"><p className="role-copy">Přehled podkladů, zjištění, opatření a historie procesu. Rozhodnutí se zaznamenává samostatně.</p>{can(assignment, 'MAKE_RVH_DECISION') && <button className="primary-button" type="button">Rozhodnutí RVH</button>}</WorkspaceCard></div> }
function QualityOfficeBody({ role }: { role: string }) { return <div className="role-grid"><WorkspaceCard title={role === 'FAKULTNI_KOORDINATOR_KVALITY' ? 'Portfolio FSI' : 'Portfolio VUT'} label="Metodický a procesní dohled"><div className="role-stat-grid"><Metric label="Aktivní procesy" value={role === 'FAKULTNI_KOORDINATOR_KVALITY' ? '3' : '6'} /><Metric label="Hodnocení v příštích 12 měsících" value="4" /><Metric label="Chybějící důkazy" value="8" /><Metric label="Opatření po termínu" value="3" /></div></WorkspaceCard><WorkspaceCard title="Procesní bottlenecks" label="Kde je potřeba zásah"><RoleTask title="2 hodnocení čekají na důkazy" detail="N-PI · N-EN" action="Metodická podpora" /><RoleTask title="Akreditační proces čeká na RVH" detail="Energetické inženýrství" action="Sledovat" /></WorkspaceCard></div> }
function LeadershipBody({ role }: { role: string }) { return <div className="role-grid"><WorkspaceCard title={role === 'VEDENI_FAKULTY' ? 'Strategické portfolio fakulty' : 'Strategické portfolio VUT'} label="Agregovaná rozhodovací podpora"><div className="role-stat-grid"><Metric label="Studijní programy" value={role === 'VEDENI_FAKULTY' ? '12' : '48'} /><Metric label="Akreditační horizont" value="6 / 24" /><Metric label="Významná zjištění" value="5" /><Metric label="Nevyřešená opatření" value="9" /></div></WorkspaceCard><WorkspaceCard title="Trendy a priority" label="Bez nízkoúrovňových editačních ovládacích prvků"><p className="role-copy">Udržitelnost programu, studijní poptávka, kvalita a akreditační horizont jsou podklady pro strategické rozhodování.</p><div className="mini-bars"><span style={{ width: '72%' }} /><span style={{ width: '58%' }} /><span style={{ width: '84%' }} /></div></WorkspaceCard></div> }
function AuditorBody({ assignment }: { assignment: RoleAssignment }) { return <div className="role-grid"><WorkspaceCard title="Zpřístupněný rozsah auditu" label="EUR-ACE / Procesní inženýrství / ProgrammeVersion 3"><div className="role-stat-grid"><Metric label="Požadavky" value="6" /><Metric label="Dostupné důkazy" value="9" /><Metric label="Hodnocení" value="4" /><Metric label="Dokumenty" value="4" /></div></WorkspaceCard><WorkspaceCard title="Auditní pracovní plocha" label="Pouze přidělený rozsah"><RoleTask title="G18 · Výsledky učení" detail="Evidence a Assessment jsou zpřístupněny" action="Vytvořit hodnocení" /><RoleTask title="Auditní zjištění" detail="Přidejte komentář pouze do auditního rozsahu" action="Vytvořit zjištění" /><p className="scope-note">Platnost přístupu: {assignment.validFrom} – {assignment.validTo}</p></WorkspaceCard></div> }
function AdminBody() { return <div className="role-grid"><WorkspaceCard title="Technická správa" label="Odděleno od akademických rozhodnutí"><div className="role-stat-grid"><Metric label="Uživatelé" value="86" /><Metric label="Role assignments" value="143" /><Metric label="Konfigurace" value="12" /><Metric label="Stav systému" value="OK" /></div></WorkspaceCard><WorkspaceCard title="Konfigurace a oprávnění" label="Pouze prototypové přehledy"><RoleTask title="Role a scopes" detail="Scoped access model" action="Spravovat" /><RoleTask title="Systémové nastavení" detail="Workflow a číselníky" action="Otevřít" /></WorkspaceCard></div> }
function SharedSignals() { return <WorkspaceCard title="Nadcházející hodnocení" label="Kvalitativní signály bez automatického verdiktu"><div className="attention-list">{workspaceAttention.slice(1, 4).map((item) => <div className="workspace-attention neutral" key={item.title}><span className="signal-dot" /><div><strong>{item.title}</strong><span>{item.detail}</span></div></div>)}</div></WorkspaceCard> }
function WorkspaceCard({ title, label, children }: { title: string; label: string; children: React.ReactNode }) { return <section className="section-panel role-card"><div className="section-panel-header"><div><h2>{title}</h2><span className="section-caption">{label}</span></div></div>{children}</section> }
function RoleTask({ title, detail, action }: { title: string; detail: string; action?: string }) { return <div className="role-task"><div><strong>{title}</strong><span>{detail}</span></div>{action && <button type="button" className="text-button">{action} →</button>}</div> }
function Metric({ label, value }: { label: string; value: string }) { return <div className="role-metric"><span>{label}</span><strong>{value}</strong></div> }